version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: wewe-rss-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wewe-rss
      - MYSQL_DATABASE=wewe_rss
      - MYSQL_USER=wewe-rss
      - MYSQL_PASSWORD=wewe-rss
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wewe-rss-network

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: wewe-rss-api
    restart: always
    environment:
      - PORT=4000
      - DATABASE_URL=mysql://wewe-rss:wewe-rss@db:3306/wewe_rss
      - DATABASE_TYPE=mysql
      - AUTH_CODE=YOUR_AUTH_CODE
      - PLATFORM_URL=http://authserver:8080
      - SERVER_ORIGIN_URL=http://localhost:4000
      - CRON_EXPRESSION=0 */20 * * * *
    ports:
      - '4000:4000'
    depends_on:
      - db
      - authserver
    networks:
      - wewe-rss-network

  authserver:
    build:
      context: ./authserver
      dockerfile: ./Dockerfile
    image: wewe-rss/authserver
    container_name: wewe-rss-authserver
    restart: always
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=false
      - DEFAULT_ARTICLES=20
    ports:
      - '8080:8080'
    networks:
      - wewe-rss-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  db_data:

networks:
  wewe-rss-network:
    name: wewe-rss-network
