version: '3.8'

services:
  authserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: wewe-rss/authserver
    container_name: wewe-rss-authserver
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=false
      - DEFAULT_ARTICLES=20 